export const benefits = [
  { icon: "strength", title: "Builds Strength Naturally", text: "Complete plant-based proteins from millets, sprouted grains, and nuts support muscle growth and recovery at every life stage — from growing children to active adults." },
  { icon: "shield", title: "Boosts Immunity", text: "Rich in antioxidants, vitamins C & A, and anti-inflammatory compounds from moringa, kashaya spices, and turmeric strengthen your body's natural defenses." },
  { icon: "leaf", title: "Easy Digestion", text: "Sprouted grains and soaked almonds release natural enzymes that unlock nutrients and make digestion effortless — an Ayurvedic practice passed down through generations." },
  { icon: "bolt", title: "Sustained Energy", text: "Complex carbohydrates from millets and fiber-rich ingredients provide slow-release energy throughout the day without the crash of refined sugars or caffeine." },
  { icon: "sun", title: "Mental Clarity", text: "High in iron, B vitamins, and essential minerals that support cognitive function, reduce brain fatigue, and improve focus and concentration." },
  { icon: "balance", title: "Hormonal Balance", text: "Fenugreek (methi) and nutrient-dense ingredients traditionally support hormonal health, especially beneficial for women during postpartum and nursing." },
  { icon: "flame", title: "Metabolic Support", text: "Natural ingredients like ginger, cinnamon, and black pepper stimulate digestive fire, support healthy metabolism, and provide gentle body warmth." },
  { icon: "drop", title: "Blood Health", text: "Rich in iron and helps maintain healthy hemoglobin levels — important for preventing anemia and supporting overall cardiovascular health." },
];

const NOTE = "100% Natural · No Artificial Additives · Farm Fresh";

export const products = [
  { id: "millet", name: "Millet Protein Powder", tag: "Complete Plant-Based Protein", img: "/images/products/protein-powder.png", tint: "#f3e6c8", leaf: ["#b98d3c", "#8a9a5b"], hl: [["100%", "Natural", "Made with foxtail millet, sprouted grains, and nuts & seeds"], ["Complete", "Plant-Based Protein", "Supports muscle growth and recovery at every life stage"], ["0", "Artificial Flavours", "Nothing artificial, only real food"]],
    desc: "A creamy everyday protein blend of foxtail millet, sprouted grains, and nuts & seeds. Complete plant-based nutrition with nothing artificial.",
    ingredients: [["Foxtail Millet", "Slow-release complex carbohydrates and fibre"], ["Sprouted Grains", "Release natural enzymes that make nutrients easier to absorb"], ["Nuts & Seeds", "Healthy fats and protein for muscle growth and recovery"]],
    cards: [["Rich in Plant Protein", "Supports muscle growth and recovery, from growing children to active adults"], ["Sustained Energy", "Slow-release energy through the day without the crash of refined sugar"], ["Easy Digestion", "High in dietary fibre, gentle on the stomach"]],
    features: ["Rich in Plant Protein", "Energy Booster", "Immunity Support", "High in Dietary Fibre", "No Artificial Flavours"],
    stats: [["100%", "Natural"], ["Complete", "Plant-based protein"], ["0", "Artificial flavours"]] },
  { id: "moringa", name: "Moringa Soup Mix", tag: "Nature's Multivitamin", img: "/images/products/Moringa.png", tint: "#e3ecd2", leaf: ["#4d7c2f", "#7aa35a"], hl: [["25x", "More Iron Than Spinach", "Helps maintain healthy hemoglobin levels"], ["7x", "More Vitamin C Than Orange", "Strengthens the body's natural defenses"], ["9x", "More Protein Than Yogurt", "Moringa and lentils for steady energy"]],
    desc: "Farm-fresh moringa leaves and lentils seasoned with turmeric and black pepper. A warm, everyday soup that works like a multivitamin.",
    ingredients: [["Moringa Leaves (Farm Fresh)", "Iron, vitamins C and A, and protein"], ["Lentils", "Plant protein and steady energy"], ["Herbs & Spices", "Flavour with traditional digestive support"], ["Rock Salt", "Gentle, natural seasoning"], ["Turmeric", "Anti-inflammatory compounds"], ["Black Pepper", "Stimulates digestive fire"]],
    cards: [["Strong Immunity", "Vitamin C and A plus anti-inflammatory compounds strengthen natural defenses"], ["Blood Health", "Rich in iron to help maintain healthy hemoglobin levels"], ["Energy Booster", "Protein and lentils give lasting energy"]],
    features: ["Rich Protein", "Energy Booster", "Strong Immunity", "Good for Skin & Hair", "Fights Bacterial Diseases"],
    stats: [["25x", "More iron than spinach"], ["7x", "More vitamin C than orange"], ["9x", "More protein than yogurt"]] },
  { id: "methi", name: "Methi Balls", tag: "Traditional Postpartum Nourishment", img: "/images/products/methi.png", tint: "#f0dfc8", leaf: ["#a86a3a", "#c9a24a"], hl: [["100%", "Natural", "Fenugreek (methi), made the traditional way"], ["Postpartum", "Nourishment", "A traditional snack that supports lactation"], ["Farm", "Fresh", "No artificial additives"]],
    desc: "A traditional postpartum snack built around fenugreek (methi), made for warmth, strength and recovery.",
    ingredients: [["Fenugreek (Methi)", "Traditionally used for hormonal balance and lactation support"]],
    cards: [["Hormonal Balance", "Traditionally supports hormonal health, especially for women during postpartum and nursing"], ["Lactation Support", "A traditional snack that supports lactation"], ["Natural Warmth", "Provides warmth, perfect as an energy bite at any time of day"]],
    features: [], stats: [["100%", "Natural"], ["0", "Artificial additives"], ["Farm", "Fresh"]] },
  { id: "kashaya", name: "Kashaya Mix", tag: "Immunity Brewing Tradition", img: "/images/products/Kashaya.png", tint: "#f1dcc4", leaf: ["#8a4b2d", "#5f8f4a"], hl: [["18", "Powerful Herbs", "A traditional South Indian decoction for daily immunity"], ["0%", "Caffeine", "A warming herbal brew with no caffeine"], ["100%", "Natural Spices", "No preservatives, artificial flavours or colours"]],
    desc: "A traditional South Indian herbal decoction made with 18 powerful herbs. Brewed as a daily immunity ritual, with no caffeine.",
    ingredients: [["Ginger", "Warming, supports digestion"], ["Tulsi", "Traditionally used for respiratory health"], ["Black Pepper", "Stimulates digestive fire"], ["Cinnamon", "Supports healthy metabolism"], ["Cardamom", "Aromatic, aids digestion"], ["Turmeric", "Anti-inflammatory compounds"]],
    cards: [["Morning Ritual", "Traditional South Indian wellness drink"], ["Anti-Inflammatory", "Reduces joint pain naturally"], ["Respiratory Health", "Clears congestion effectively"]],
    features: ["Immunity Booster", "Digestive Support", "Body Cleanser", "Rich in Antioxidants", "Relieve Stress", "Prevent Cough, Cold"],
    stats: [["100%", "Natural Spices"], ["0%", "Caffeine"], ["5+", "Spices"]] },
];

const P = Object.fromEntries(products.map((p) => [p.id, p]));

export const recipes = [
  { slug: "golden-millet-protein-smoothie", title: "Golden Millet Protein Smoothie", cat: "Shakes & Smoothies", art: "shake", time: "5 mins", product: P.millet,
    blurb: "A creamy, energizing smoothie perfect for post-workout recovery or a quick breakfast. Packed with complete protein and healthy fats.",
    ingredients: ["2 tbsp Millet Protein Powder", "1 ripe banana", "1 cup milk (dairy or almond)", "1 tsp honey or jaggery", "A pinch of turmeric and cardamom", "Ice cubes, optional"],
    steps: ["Add everything to a blender.", "Blend for about a minute until completely smooth.", "Taste, adjust sweetness, and serve immediately."] },
  { slug: "chocolate-millet-milkshake", title: "Chocolate Millet Milkshake", cat: "Shakes & Smoothies", art: "shake", time: "5 mins", product: P.millet,
    blurb: "A thick, cold chocolate shake with a serious protein boost, the kind you can drink after a workout.",
    ingredients: ["2 tbsp Millet Protein Powder", "1 cup cold milk", "1 tbsp unsweetened cocoa powder", "1 tbsp jaggery syrup or honey", "4 ice cubes"],
    steps: ["Blend milk, protein powder, cocoa and sweetener until smooth.", "Add the ice and blend 30 seconds more.", "Pour into a tall glass and serve at once."] },
  { slug: "millet-protein-chocolate-bars", title: "Millet Protein Chocolate Bars", cat: "Chocolate Bars", art: "choco", time: "20 mins + chilling", product: P.millet,
    blurb: "No-bake bars with a dark chocolate top. Cut them small and keep them in the fridge for busy days.",
    ingredients: ["1/2 cup Millet Protein Powder", "1/2 cup rolled oats", "1/3 cup peanut or almond butter", "3 tbsp honey", "60 g dark chocolate", "1 tsp coconut oil"],
    steps: ["Mix powder, oats, nut butter and honey into a thick dough.", "Press firmly into a lined tin.", "Melt chocolate with coconut oil, spread on top, and chill for an hour.", "Cut into bars."] },
  { slug: "dark-chocolate-protein-truffles", title: "Dark Chocolate Protein Truffles", cat: "Chocolate Bars", art: "choco", time: "15 mins", product: P.millet,
    blurb: "Soft date truffles rolled in cocoa: a small, rich bite with no refined sugar.",
    ingredients: ["10 pitted dates", "3 tbsp Millet Protein Powder", "2 tbsp cocoa powder plus extra for rolling", "1 tbsp melted coconut oil", "Pinch of salt"],
    steps: ["Blend the dates to a sticky paste.", "Add protein powder, cocoa, oil and salt and pulse until it holds together.", "Roll into balls and coat in cocoa. Chill before serving."] },
  { slug: "millet-protein-banana-cake", title: "Millet Protein Banana Cake", cat: "Cakes & Bakes", art: "cake", time: "50 mins", product: P.millet,
    blurb: "A moist, lightly sweet loaf cake made with jaggery. Good with tea and better on day two.",
    ingredients: ["1/2 cup Millet Protein Powder", "1 cup whole wheat flour", "2 ripe bananas", "1/3 cup jaggery powder", "1/4 cup oil or melted ghee", "1/2 cup milk", "1 tsp baking powder"],
    steps: ["Heat the oven to 180 C and grease a loaf tin.", "Mash the bananas and whisk with jaggery, oil and milk.", "Fold in the flour, protein powder and baking powder until just combined.", "Bake 30 to 35 minutes until a skewer comes out clean."] },
  { slug: "moringa-savoury-muffins", title: "Moringa Savoury Muffins", cat: "Cakes & Bakes", art: "cake", time: "30 mins", product: P.moringa,
    blurb: "Green-flecked savoury muffins for lunchboxes, flavoured with cumin and grated carrot.",
    ingredients: ["1 cup whole wheat flour", "2 tbsp Moringa Soup Mix", "1/2 cup curd", "1/4 cup milk", "1/4 cup oil", "1/4 cup grated carrot", "1 tsp baking powder", "1/2 tsp cumin seeds"],
    steps: ["Heat the oven to 180 C and grease a muffin tray.", "Whisk curd, milk and oil, then stir in the carrot and cumin.", "Fold in the flour, soup mix and baking powder. Do not overmix.", "Spoon into the tray and bake for 18 to 20 minutes."] },
  { slug: "moringa-immunity-bowl", title: "Moringa Immunity Bowl", cat: "Soups & Kashaya", art: "soup", time: "10 mins", product: P.moringa,
    blurb: "A warm, nourishing soup rich in vitamins and antioxidants. Perfect for boosting immunity during seasonal changes.",
    ingredients: ["2 tbsp Moringa Soup Mix", "2 cups water", "1/2 cup cooked foxtail millet", "1/4 cup steamed carrot and beans", "1 tsp ghee", "Lemon wedge"],
    steps: ["Whisk the soup mix into cold water so it does not clump.", "Bring to a gentle simmer for 5 to 6 minutes, stirring often.", "Spoon the cooked millet and vegetables into a bowl and pour the soup over.", "Finish with ghee and a squeeze of lemon."] },
  { slug: "kashaya-morning-brew", title: "Kashaya Morning Brew", cat: "Soups & Kashaya", art: "cup", time: "10 mins", product: P.kashaya,
    blurb: "The classic South Indian herbal decoction, brewed slowly on the stove. Caffeine-free and best sipped warm.",
    ingredients: ["1 tsp Kashaya Mix", "2 cups water", "Jaggery or honey to taste", "A splash of milk, optional"],
    steps: ["Bring the water to a boil and stir in the Kashaya Mix.", "Simmer on low for 5 to 7 minutes until it reduces by about a quarter.", "Strain into a cup and sweeten with jaggery once it stops bubbling."] },
  { slug: "kashaya-masala-milk", title: "Kashaya Masala Milk", cat: "Soups & Kashaya", art: "cup", time: "10 mins", product: P.kashaya,
    blurb: "A softer, creamier take on kashaya for evenings and cold nights.",
    ingredients: ["1 tsp Kashaya Mix", "1 cup water", "1/2 cup milk", "1 tsp jaggery"],
    steps: ["Simmer the Kashaya Mix in the water for 5 minutes.", "Add the milk and warm through without boiling hard.", "Strain, stir in jaggery and serve hot."] },
  { slug: "millet-protein-porridge", title: "Millet Protein Porridge", cat: "Breakfast", art: "bowl", time: "10 mins", product: P.millet,
    blurb: "A thick, comforting porridge for slow mornings, topped with dates and nuts.",
    ingredients: ["3 tbsp Millet Protein Powder", "1 cup milk", "1/2 tsp cardamom powder", "2 chopped dates", "Handful of chopped nuts"],
    steps: ["Whisk the powder into cold milk until smooth.", "Cook on low heat for 4 to 5 minutes, stirring, until thick.", "Stir in cardamom, then top with dates and nuts."] },
  { slug: "millet-protein-pancakes", title: "Millet Protein Pancakes", cat: "Breakfast", art: "stack", time: "20 mins", product: P.millet,
    blurb: "Fluffy banana pancakes with extra protein. Serve with honey or fruit.",
    ingredients: ["1/2 cup Millet Protein Powder", "1/2 cup whole wheat flour", "1 ripe banana", "3/4 cup milk", "1 tsp baking powder", "Ghee for the pan"],
    steps: ["Mash the banana and whisk with the milk.", "Stir in the powder, flour and baking powder to a thick batter and rest 5 minutes.", "Cook spoonfuls on a ghee-greased pan over medium heat, 2 minutes per side."] },
  { slug: "traditional-methi-ladoo", title: "Traditional Methi Ladoo", cat: "Sweets & Snacks", art: "ladoo", time: "20 mins", product: P.methi,
    blurb: "A traditional postpartum snack that supports lactation and provides warmth. Perfect energy bites for any time of day.",
    ingredients: ["1 cup Methi Balls (crushed)", "1/2 cup jaggery powder", "2 tbsp ghee", "2 tbsp chopped almonds", "1/2 tsp dry ginger powder"],
    steps: ["Warm the ghee on low heat and roast the crushed methi balls for 3 to 4 minutes.", "Add almonds and dry ginger and stir for a minute.", "Turn off the heat, let it cool for 2 minutes, then mix in the jaggery powder.", "While still warm, press into small ladoos. Store airtight."] },
  { slug: "millet-protein-ladoo", title: "Millet Protein Ladoo", cat: "Sweets & Snacks", art: "ladoo", time: "20 mins", product: P.millet,
    blurb: "Roasted-powder ladoos with ghee and jaggery, made like a festival sweet and packed like a snack.",
    ingredients: ["1 cup Millet Protein Powder", "3 tbsp ghee", "1/2 cup jaggery powder", "1/2 tsp cardamom powder"],
    steps: ["Dry roast the powder on low heat for 3 to 4 minutes until fragrant.", "Stir in the warm ghee, then the jaggery and cardamom off the heat.", "Shape into ladoos while the mixture is still warm."] },
  { slug: "moringa-millet-khichdi", title: "Moringa Millet Khichdi", cat: "Mains", art: "bowl", time: "25 mins", product: P.moringa,
    blurb: "One-pot comfort food with foxtail millet and moong dal, finished with moringa.",
    ingredients: ["1/2 cup foxtail millet", "1/4 cup split moong dal", "2 tbsp Moringa Soup Mix", "1 tsp ghee", "1/2 tsp cumin seeds", "2 1/2 cups water"],
    steps: ["Rinse the millet and dal together.", "Heat ghee, crackle the cumin, then add millet, dal, and water.", "Pressure cook for 3 whistles, or simmer covered for 20 minutes.", "Dissolve the soup mix in a little water, stir it in, and simmer 3 minutes. Add salt only if needed."] },
];

export const categories = [
  { name: "Shakes & Smoothies", blurb: "Cold, creamy and protein-rich." },
  { name: "Chocolate Bars", blurb: "No-bake bars and bites." },
  { name: "Cakes & Bakes", blurb: "Soft loaves and savoury muffins." },
  { name: "Soups & Kashaya", blurb: "Warm bowls and herbal brews." },
  { name: "Breakfast", blurb: "Slow mornings, made simple." },
  { name: "Sweets & Snacks", blurb: "Traditional ladoos, made properly." },
  { name: "Mains", blurb: "One-pot comfort food." },
];
